### ISSUE TITLE
dropcap styling

### ISSUE THREAD

**Issue by acabal** [drgrigg/rudyard-kipling_just-so-stories#6]
Instead of using `class="dropcap"` can we use `p img`?

**Comment by acabal** [comment]
Additionally we can probably name these files more accurately, something like `dropcap-t.svg` or `dropcap-i-1.svg`/`dropcap-i-2.svg` to differentiate them from the actual illustrations

**Comment by drgrigg** [comment]
Should these also be within <figure> tags? That would complicate the CSS even more, though!

To be honest, I'm kind of tempted to remove them altogether, since I'm not actually using them as real drop caps (because I haven't used them to replace the first letter of the text), and I've hit at least one ereader program which ignores the 'float' and puts them in stretched to page width, which looks really ugly. Even in the printed book, they don't work very well as drop caps, as in many cases it's quite hard to figure out what letter is being represented.

What do you think?

**Comment by acabal** [comment]
No, because they're not a "figure" but (ostensibly) just a fancy decorative letter. So the markup is fine as-is.

I investigated some ways to maybe make these image drop caps work while hiding the first letter. None of them really worked out.  The `::first-letter` selector was promising but it doesn't work if the first child is an image, or if you use `::before`.  Targeting a custom attribute also doesn't work because we can't specify the size of an image using `content`. We could wrap the first letter in a span but that's kind of sloppy. So all in all it's kind of a bummer.

So I suppose I'm also OK with removing them, if you want. (Personally I never liked drop caps in general anyway.)

**Comment by drgrigg** [comment]
Yeah, I think I would prefer to remove them. I might leave the (renamed) source PNG files in the top level root/images folder so that if some future producer wants to include them, they can.
